# Generated by Django 2.1.3 on 2018-11-14 15:38

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('type_id', models.CharField(choices=[(1, 'Python'), (2, 'algrithm and data sturcture'), (4, 'mechinelearning'), (5, 'operating system'), (6, 'database management')], default=1, max_length=10, verbose_name='books category')),
                ('name', models.CharField(max_length=20, verbose_name='books name')),
                ('desc', models.CharField(max_length=128, verbose_name='books describe')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='books price')),
                ('unit', models.CharField(max_length=20, verbose_name='books unit')),
                ('stock', models.IntegerField(default=1, verbose_name='books stock')),
                ('sales', models.IntegerField(default=0, verbose_name='sales of books')),
                ('detail', tinymce.models.HTMLField(verbose_name='detail of book')),
                ('image', models.ImageField(upload_to='books', verbose_name='image of book')),
                ('status', models.SmallIntegerField(choices=[(0, 'off line'), (1, 'on line')], default=1, verbose_name='status of book')),
            ],
            options={
                'verbose_name': 'books',
                'verbose_name_plural': 'books',
                'db_table': 's_books',
            },
        ),
    ]
