# Generated by Django 2.1.3 on 2018-11-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_address'),
        ('books', '0003_auto_20181116_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('count', models.IntegerField(default=1, verbose_name='book count')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('books', models.ForeignKey(on_delete=True, to='books.Books', verbose_name='book id')),
            ],
            options={
                'db_table': 's_order_books',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('is_delete', models.BooleanField(default=False, verbose_name='delete mark')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='order id')),
                ('total_count', models.IntegerField(default=1, verbose_name='book number')),
                ('transit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='express price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待发货'), (3, '待收货'), (4, '待评价'), (5, '已完成')], default=1, verbose_name='order status')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '货到付款'), (2, '微信支付'), (3, '支付宝'), (4, '银联支付')], default=1, verbose_name='pay method')),
                ('trade_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='trade number')),
                ('addr', models.ForeignKey(on_delete=True, to='users.Address', verbose_name='address')),
                ('passport', models.ForeignKey(on_delete=True, to='users.Passport', verbose_name='user')),
            ],
            options={
                'db_table': 's_order_info',
            },
        ),
        migrations.AddField(
            model_name='orderbooks',
            name='order',
            field=models.ForeignKey(on_delete=True, to='order.OrderInfo', verbose_name='order id'),
        ),
    ]
